[package]
name = "adventofcode"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
csv = "1.3.1"
faer = "0.19.4"
ndarray = "0.16.1"
serde = { version = "1.0.215", features = ["derive"] }
